
# Using busybox image - replicates a lightweight utility

apiVersion: v1
kind: ReplicationController
metadata:
  name: busybox-rc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox-container
        image: busybox