#Using alpine image - replicates a minimal Linux distribution

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: alpine-rs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alpine
  template:
    metadata:
      labels:
        app: alpine
    spec:
      containers:
      - name: alpine-container
        image: alpine